# Generated by Django 6.1.1 on 2026-10-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0003_frameworkrequirement_controlrequirement'),
        ('risks', '0003_risk_residual_impact_risk_residual_likelihood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='assessment ID')),
                ('title', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('control_test', 'Control test'), ('risk_review', 'Risk review')], max_length=20, verbose_name='type')),
                ('review_date', models.DateField()),
                ('reviewer', models.CharField(help_text='Person or role.', max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('complete', 'Complete')], default='planned', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('satisfactory', 'Satisfactory'), ('partial', 'Partially satisfactory'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True, help_text='What was looked at. A written description, not an uploaded file.')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='controls.control')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='risks.risk')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
