# Generated by Django 6.1.1 on 2026-10-07 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('controls', '0003_frameworkrequirement_controlrequirement'),
        ('processes', '0002_processcontrol'),
        ('risks', '0004_risk_process_alter_risk_risk_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='processes.process'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('control_test', 'Control test'), ('risk_review', 'Risk review'), ('process_review', 'Process or solution review')], max_length=20, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='AssessedControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.BooleanField(default=False, help_text='Untick to leave this control out of this review.')),
                ('outcome', models.CharField(blank=True, choices=[('satisfactory', 'Satisfactory'), ('partial', 'Partially satisfactory'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('likelihood', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Rare'), (2, '2 – Unlikely'), (3, '3 – Possible'), (4, '4 – Likely'), (5, '5 – Almost certain')], null=True)),
                ('impact', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Insignificant'), (2, '2 – Minor'), (3, '3 – Moderate'), (4, '4 – Major'), (5, '5 – Severe')], null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_results', to='assessments.assessment')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risks.riskcategory')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_assessment_lines', to='controls.control')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_control_lines', to='risks.risk')),
            ],
            options={
                'ordering': ['control__control_id'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'control'), name='one_control_line_per_assessment')],
            },
        ),
        migrations.CreateModel(
            name='AssessedRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.BooleanField(default=False, help_text='Tick to reassess this risk in this review.')),
                ('findings', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('likelihood', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Rare'), (2, '2 – Unlikely'), (3, '3 – Possible'), (4, '4 – Likely'), (5, '5 – Almost certain')], null=True)),
                ('impact', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Insignificant'), (2, '2 – Minor'), (3, '3 – Moderate'), (4, '4 – Major'), (5, '5 – Severe')], null=True)),
                ('close_risk', models.BooleanField(default=False, help_text='Tick only when this risk should be closed.', verbose_name='close this risk')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_reviews', to='assessments.assessment')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reassessments', to='risks.risk')),
            ],
            options={
                'ordering': ['risk__risk_id'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'risk'), name='one_risk_line_per_assessment')],
            },
        ),
    ]
