# Adds the risk-register fields to a process or solution review, so a review
# can add a risk or update one. Generated by Django 6.1.1 on 2026-10-07.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_process_alter_assessment_assessment_type_and_more'),
        ('risks', '0004_risk_process_alter_risk_risk_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessedrisk',
            name='acceptance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='acceptance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risks.riskcategory'),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='date_identified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='owner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='residual_impact',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Insignificant'), (2, '2 – Minor'), (3, '3 – Moderate'), (4, '4 – Major'), (5, '5 – Severe')], null=True),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='residual_likelihood',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Rare'), (2, '2 – Unlikely'), (3, '3 – Possible'), (4, '4 – Likely'), (5, '5 – Almost certain')], null=True),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='response_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='response_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='risk_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='risk_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assessedrisk',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assessedrisk',
            name='close_risk',
            field=models.BooleanField(default=False, help_text='Set when the status on this line is Closed.', verbose_name='close this risk'),
        ),
        migrations.AlterField(
            model_name='assessedrisk',
            name='include',
            field=models.BooleanField(default=False, help_text='Tick to assess this risk in this review.'),
        ),
        migrations.AlterField(
            model_name='assessedrisk',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reassessments', to='risks.risk'),
        ),
    ]
