# Generated by Django 6.1.1 on 2026-10-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='control ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('owner', models.CharField(help_text='Person or role.', max_length=200)),
                ('control_type', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective')], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_place', 'In place'), ('not_operating', 'Not operating')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
