# Generated by Django 6.1.1 on 2026-10-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
        ('risks', '0002_riskchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectiveness', models.CharField(choices=[('effective', 'Effective'), ('partial', 'Partially effective'), ('ineffective', 'Ineffective')], max_length=20)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_links', to='controls.control')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_links', to='risks.risk')),
            ],
            options={
                'ordering': ['control__control_id'],
                'constraints': [models.UniqueConstraint(fields=('risk', 'control'), name='one_link_per_risk_and_control')],
            },
        ),
    ]
