# Generated by Django 6.1.1 on 2026-10-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_riskcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.CharField(choices=[('iso_27001', 'ISO 27001'), ('nist_csf', 'NIST CSF'), ('soc_2', 'SOC 2')], max_length=20)),
                ('reference', models.CharField(help_text="The requirement's own identifier, for example A.5.15 or PR.AA-01.", max_length=30)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'framework requirement',
                'ordering': ['framework', 'reference'],
                'constraints': [models.UniqueConstraint(fields=('framework', 'reference'), name='one_reference_per_framework')],
            },
        ),
        migrations.CreateModel(
            name='ControlRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_links', to='controls.control')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_links', to='controls.frameworkrequirement')),
            ],
            options={
                'verbose_name': 'framework mapping',
                'ordering': ['requirement__framework', 'requirement__reference'],
                'constraints': [models.UniqueConstraint(fields=('control', 'requirement'), name='one_mapping_per_control_and_requirement')],
            },
        ),
    ]
