# Generated by Django 6.1.1 on 2026-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('process', 'Process'), ('solution', 'Solution')], max_length=20, verbose_name='type')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('owner', models.CharField(help_text='Person or role.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
