# Generated by Django 6.1.1 on 2026-10-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_frameworkrequirement_controlrequirement'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_links', to='controls.control')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_links', to='processes.process')),
            ],
            options={
                'ordering': ['control__control_id'],
                'constraints': [models.UniqueConstraint(fields=('process', 'control'), name='one_link_per_process_and_control')],
            },
        ),
    ]
