# Generated by Django 6.1.1 on 2026-10-05 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'risk categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='risk ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('owner', models.CharField(help_text='Person or role.', max_length=200)),
                ('risk_source', models.CharField(help_text='Where the risk resides, e.g. a process or a solution/system.', max_length=200)),
                ('date_identified', models.DateField(default=django.utils.timezone.localdate)),
                ('inherent_likelihood', models.PositiveSmallIntegerField(choices=[(1, '1 – Rare'), (2, '2 – Unlikely'), (3, '3 – Possible'), (4, '4 – Likely'), (5, '5 – Almost certain')])),
                ('inherent_impact', models.PositiveSmallIntegerField(choices=[(1, '1 – Insignificant'), (2, '2 – Minor'), (3, '3 – Moderate'), (4, '4 – Major'), (5, '5 – Severe')])),
                ('inherent_score', models.PositiveSmallIntegerField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_treatment', 'In treatment'), ('monitoring', 'Monitoring'), ('closed', 'Closed')], default='open', max_length=20)),
                ('response_type', models.CharField(blank=True, choices=[('mitigate', 'Mitigate'), ('accept', 'Accept'), ('transfer', 'Transfer'), ('avoid', 'Avoid')], max_length=20, verbose_name='risk response type')),
                ('response_description', models.TextField(blank=True, verbose_name='risk response description')),
                ('accepted_by', models.CharField(blank=True, help_text='Person or role who signed off.', max_length=200)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('acceptance_expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risks.riskcategory')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('inherent_likelihood__gte', 1), ('inherent_likelihood__lte', 5)), name='inherent_likelihood_1_to_5'), models.CheckConstraint(condition=models.Q(('inherent_impact__gte', 1), ('inherent_impact__lte', 5)), name='inherent_impact_1_to_5')],
            },
        ),
    ]
