# Generated by Django 6.1.1 on 2026-10-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_riskchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='residual_impact',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Insignificant'), (2, '2 – Minor'), (3, '3 – Moderate'), (4, '4 – Major'), (5, '5 – Severe')], null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='residual_likelihood',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 – Rare'), (2, '2 – Unlikely'), (3, '3 – Possible'), (4, '4 – Likely'), (5, '5 – Almost certain')], help_text='After controls. Leave both residual scores blank until this has been assessed.', null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='residual_score',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.CheckConstraint(condition=models.Q(('residual_likelihood__isnull', True), models.Q(('residual_likelihood__gte', 1), ('residual_likelihood__lte', 5)), _connector='OR'), name='residual_likelihood_1_to_5_or_empty'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.CheckConstraint(condition=models.Q(('residual_impact__isnull', True), models.Q(('residual_impact__gte', 1), ('residual_impact__lte', 5)), _connector='OR'), name='residual_impact_1_to_5_or_empty'),
        ),
    ]
