# Generated by Django 6.1.1 on 2026-10-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
        ('risks', '0003_risk_residual_impact_risk_residual_likelihood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='process',
            field=models.ForeignKey(help_text='Every risk belongs to one process or solution.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='processes.process', verbose_name='process or solution'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_source',
            field=models.CharField(help_text='Where the risk shows up in more detail, e.g. a system or a team.', max_length=200),
        ),
    ]
